### PR TITLE
Fix the %$&@£ storage test

### PR DESCRIPTION
**Pull request by alicefuzier**

### CODE REVIEW

**Comment by alexwlchan** [comment]
Not to be a party-pooper, but this is going into the wrong repo. :'(

**Comment by alicefuzier** [comment]
Moved to https://github.com/wellcometrust/scala-storage/pull/5

**Comment by alicefuzier** [comment]
Since migration to scala-storage is taking longer than expected, I'd like to puthis in here, cause this is getting frustrating

**Comment by alicefuzier** [comment]
I'm also going to merge it as is cause I don't want to have to restart another storage test

**Comment by alexwlchan** [comment]
👍👍👍

**Pull request merged**
