### PR TITLE
Adds catalogue_vpc to shared_infra

### PR DESCRIPTION
**Pull request by kenoir**
### What is this PR trying to achieve?

Reduce the number of VPCs we have by consolidating all adapters and APIs into the same VPC using public/private subnets to ensure private services are not user facing.

### Who is this change for?

Folk who want simpler more sensible infrastructure.

### CODE REVIEW

**Comment by alexwlchan** [comment]
Is anybody going to use this new VPC?

**Comment by kenoir** [comment]
@alexwlchan everybody! It's the new hot VPC to be placed in!

**Comment by alexwlchan** [comment]
So are the changes to use it coming in a separate patch?

**Comment by kenoir** [comment]
Yup, first thing is to move `sierra_adapter` to it and then carry on moving things to the new infra while using this VPC.

**Pull request merged**
