### PR TITLE
Create a table of contents for RFCs

### PR DESCRIPTION
**Pull request by alexwlchan**
This adds a table of contents to the RFCs folder, so somebody looking at the folder knows what documents are available. Hopefully this makes it a bit more useful than just plain folder slugs!

### CODE REVIEW

**Comment by kenoir** [comment]
Great plan 👍

**Comment by alexwlchan** [comment]
Yes it should, but I started this before you moved all the docs over. 😉

**Comment by alexwlchan** [comment]
I have a replacement for this on my iMac at home, but I don't have write access to the docs repo.

**Comment by kenoir** [comment]
Closed as docs have moved.

**Pull request closed without merging**
