### PR TITLE
[WIP] dynamo_to_sns should send messages concurrently

### PR DESCRIPTION
**Pull request by alexwlchan**
Mark and I looked at the code for ThreadPoolExecutor and I’m pretty sure it waits until everything is done before cleaning up – but we should have some tests for sending multiple messages.

### CODE REVIEW

**Comment by mklander** [comment]
Looks like this worked for the latest reindex.  Lambda average execution times are lower (~ 1/2) than the previous run.

**Comment by kenoir** [comment]
@alexwlchan can we de-wip?

**Comment by alexwlchan** [comment]
@kenoir Nope, still needs automated tests.

**Comment by alexwlchan** [comment]
Rather distressingly, the test crashes out somewhere in boto3:

```
self = <botocore.parsers.QueryParser object at 0x7fbae161f668>
parsed = {'div': [<Element 'div' at 0x7fbae16a4908>, <Element 'div' at 0x7fbae16a4e58>, <Element 'div' at 0x7fbae1008818>, <Ele...e1008958>, <Element 'div' at 0x7fbae0f8f368>, <Element 'div' at 0x7fbae0f8f4a8>], 'p': <Element 'p' at 0x7fbae0fa6458>}

    def _replace_nodes(self, parsed):
        for key, value in parsed.items():
>           if value.getchildren():
E           AttributeError: 'list' object has no attribute 'getchildren'
```

This could be an error in our mock container, or our code, or something else. Only 35 of 50 messages are successfully sent.

**Comment by alexwlchan** [comment]
Closing until somebody has more time to spend on this.

**Pull request closed without merging**
